### ISSUE TITLE
Release VisionZip model checkpoints on Hugging Face

### ISSUE THREAD

**Issue by NielsRogge** [dvlab-research/VisionZip#2] opened 2024-12-09 15:02 UTC
Hello @Yangsenqiao 🤗

I'm Niels and work as part of the open-source team at Hugging Face. I discovered your work through Hugging Face's daily papers as yours got featured: https://huggingface.co/papers/2412.04467.
The paper page lets people discuss about your paper and lets them find artifacts about it (your models for instance),
you can also claim the paper as yours which will show up on your public profile at HF.

I noticed you've released a demo and visualization of VisionZip. Would you consider hosting the pre-trained model checkpoints on the Hugging Face Model Hub? 
Hosting on Hugging Face will give you more visibility/enable better discoverability. We can add tags in the model cards so that people find the models easier,
link it to the paper page, etc.

If you're down, here's a guide: [https://huggingface.co/docs/hub/models-uploading](https://huggingface.co/docs/hub/models-uploading). If it's a custom PyTorch model, you can use the [PyTorchModelHubMixin](https://huggingface.co/docs/huggingface_hub/package_reference/mixins#huggingface_hub.PyTorchModelHubMixin)
class which adds `from_pretrained` and `push_to_hub` to the model which lets you to upload the model and people to download and use models right away.
If you do not want this and directly want to upload model through UI or however you want, people can also use [hf_hub_download](https://huggingface.co/docs/huggingface_hub/en/guides/download#download-a-single-file).

After uploaded, we can also link the models to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your model.

You can also build a demo for your model on [Spaces](https://huggingface.co/spaces), we can provide you an A100 grant.

Let me know if you're interested/need any guidance :)

Kind regards,

Niels

**Comment by Yangsenqiao** [comment] 2024-12-10 15:35
Hi Niels,

Thank you for your kind recognition! We are excited to share our work on Hugging Face. As noted in issue #3 , people think our demo is interesting, and we hope to optimize it and deploy it on Hugging Face.

Could you kindly provide your email address or other contact details so we can reach out if we encounter any issues?
For your reference, my email is: yangsenqiao.ai@gmail.com

Best regards,
Senqiao

**Comment by NielsRogge** [comment] 2024-12-10 19:37
Hi,

Sure, it looks like you've set up a demo which is nice :) refer to https://huggingface.co/docs/hub/en/spaces-sdks-gradio#create-a-new-gradio-space for details.

Feel free to reply on this thread if you face any issues

**Comment by Yangsenqiao** [comment] 2024-12-16 17:48
Hi Niels,

I hope this message finds you well.

I have uploaded my code to the [Space](https://huggingface.co/spaces/Senqiao/VisionZip), which is the same as the new ['demo-chat' branch](https://github.com/dvlab-research/VisionZip/tree/demo-chat) deployed on our [Demo-Chat](http://202.104.135.156:7860/) web platform. The environment setup follows the instructions from the [LLaVA-1.5 repository](https://github.com/haotian-liu/LLaVA#install), but I am encountering environment-related errors during deployment, as shown in the error log in the figure below.

I’m not entirely familiar with the specifics of setting up the environment on Huggingface Spaces, especially with commands like `pip install -e`. Could you kindly assist me in resolving these issues, or provide a tutorial on setting up the latest LLaVA 1.5 environment within a Huggingface Space?

Thank you in advance for your help.

Best regards,  
Senqiao

![image](https://github.com/user-attachments/assets/93dd73d3-f211-4019-a87f-445e1e14bfbf)

**Comment by NielsRogge** [comment] 2024-12-16 20:33
Pinging @hysts here who might help out

**Comment by Yangsenqiao** [comment] 2024-12-17 09:45
Thanks for your help! :heart_eyes: It looks like the error was due to an incorrect model path. I'll fix it and update the environment as you suggested.

**Comment by Yangsenqiao** [comment] 2024-12-17 10:40
Hi @hysts ,

I have updated the environment and ensured that two Gradio apps are not launched simultaneously in the [Space](https://huggingface.co/spaces/Senqiao/VisionZip). However, I am still encountering some environment errors, as shown below:

```
=================================== BUG REPORT ===================================
/home/user/.pyenv/versions/3.10.16/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

================================================================================
The following directories listed in your path were found to be non-existent:
{PosixPath('/usr/etc/pyenv.d'), PosixPath('/usr/lib/pyenv/hooks'), PosixPath('/usr/local/etc/pyenv.d'), PosixPath('/etc/pyenv.d')}
The following directories listed in your path were found to be non-existent:
{PosixPath('Europe/Paris')}
python -m bitsandbytes

The following directories listed in your path were found to be non-existent:
{PosixPath('443'), PosixPath('tcp'), PosixPath('//172.20.0.1')}
The following directories listed in your path were found to be non-existent:
{PosixPath('Senqiao/VisionZip')}
The following directories listed in your path were found to be non-existent:
{PosixPath('443'), PosixPath('tcp'), PosixPath('//172.20.0.1')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.
  warn(msg)
CUDA SETUP: To manually override the PyTorch CUDA version, please see:
https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/user/.pyenv/versions/3.10.16/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x
python setup.py install
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.16/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/user/.pyenv/versions/3.10.16/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/user/app/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/home/user/app/llava/model/__init__.py)
```

Could you provide any insight or suggestions on resolving these issues?

Thank you.

**Comment by NielsRogge** [comment] 2024-12-17 18:14
I'm afraid this is quite specific to your use case.

I would recommend taking a look at the original LlaVa demo: https://huggingface.co/spaces/badayvedat/LLaVA.

Otherwise, feel free to debug using tools like claude.ai or hf.co/chat (with Qwen-32B-coder) :)

**Comment by hysts** [comment] 2024-12-18 04:03
@Yangsenqiao You should remove https://huggingface.co/spaces/Senqiao/VisionZip/blob/5b3e7a3dfcc05d7cdefd46f1a7da1cc9d28808fa/requirements.txt#L1.

**Comment by Yangsenqiao** [comment] 2024-12-21 11:55
Hi @hysts,

Thank you and @NielsRogge for your help. Following your suggestion, I reviewed the configuration on [this page](https://huggingface.co/spaces/badayvedat/LLaVA) and made the corresponding changes to my code at [this link](https://huggingface.co/spaces/Senqiao/VisionZip/blob/main/app.py).
 The code in [app_dev_debug.py](https://huggingface.co/spaces/Senqiao/VisionZip/blob/main/app_dev_debug.py) is same to `app.py`, and I use it in development mode for debugging.

When running in development mode with the command:

```
gradio app_dev_debug.py
```

The application runs successfully, as shown in the following screenshots:


![successful output](https://github.com/user-attachments/assets/d99d32fc-ac0a-4b75-a92c-5da6295acee3)
![successful output](https://github.com/user-attachments/assets/1d8adf20-b0ed-4e82-bb3c-606c07de6b37)

**However**, when I copy the code from `app_dev_debug.py` to `app.py` and push it to the Hugging Face space, then restart the space, I encounter errors. Initially, the code runs as expected, as shown below:

![initial run](https://github.com/user-attachments/assets/bfdea877-c67b-4113-8918-e39149163b0a)
![initial run](https://github.com/user-attachments/assets/d06bf39b-498c-4d32-8e21-2877354cb57c)

**However, no interactive UI appears on the space, and the following error messages appear in the logs, indicating a possible issue related to the Space platform:**

![error log](https://github.com/user-attachments/assets/6e0a54e6-490b-409b-93a2-915e9d10e2af)

I believe we are very close to finalizing the deployment, and I would sincerely appreciate any further assistance you can provide.

Best regards,  
Senqiao

**Comment by hysts** [comment] 2024-12-24 01:41
@Yangsenqiao Apparently the issue is resolved by disabling dev mode.
The dev mode is still a beta feature and your Space launches multiple servers, so I guess it's related, but I don't know why the weird behavior happened.

![](https://github.com/user-attachments/assets/073a0927-9185-4e4b-a5b6-ecd3d3ab873e)

**Comment by Yangsenqiao** [comment] 2024-12-24 13:59
Wow🥰, thank you so much for your help! 

The last thing I’d like to ask is whether it might be possible to slightly increase my GPU quota. Currently, the L40 performs similarly to my original 3090, which is only sufficient for supporting 7B models. However, I’d love to deploy a 13B model as well to allow everyone to better compare and utilize our demo.  

That said, if this poses any difficulty on your end, that’s completely all right. Once again, I truly appreciate all your support during this time! Merry Christmas! 🎄

**Comment by hysts** [comment] 2024-12-25 03:04
@Yangsenqiao 
OK, I just switched the hardware from L4 (24GB VRAM) to L40S (48GB VRAM) for now.
But, in the long term, it would be preferable if you could migrate to ZeroGPU (underlying hardware is A100 with 40GB VRAM). ([docs](https://huggingface.co/zero-gpu-explorers))
We are using ZeroGPU as the default hardware for grants. As multiple ZeroGPU Spaces shares underlying hardwares, it helps reduce our infra cost. The A100 @NielsRogge mentioned in the first comment is actually ZeroGPU.

I assigned L4 to your Space instead of ZeroGPU because I knew the original LLaVA implementation doesn't work with ZeroGPU. (LLaVA code launches multiple processes, and it requires a dedicated GPU for model serving, but ZeroGPU doesn't work with such code.)

But LLaVA-NeXT is integrated into transformers and has a [ZeroGPU Space](https://huggingface.co/spaces/merve/llava-next). (The Space is currently not working properly for some reason, though.) Also, LLaVA is available in transformers too. https://huggingface.co/docs/transformers/main/en/model_doc/llava
So, maybe you can integrate your model into transformers and make a ZeroGPU Space based on those codes.

I hope this helps. Happy holidays! 🎉

**Comment by Yangsenqiao** [comment] 2024-12-25 16:54
I will try to integrate it into Transformers soon, and I will temporarily close this issue. Thanks again for your help, and happy holidays! 🎉

**Closed** 2024-12-25 16:56 UTC
